#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: restart logstash-docker
  docker:
    name: logstash
    image: logstash
    state: restarted
    docker_api_version: "{{ docker_api_version }}"


